Feature/nav bar
TritonSE/CCIDC-Application-Overhaul pull request #15
Opened 2024-02-05 19:06 UTC by leo3friedman

## Tracking Info

Resolves #5

## Changes

- Added nav bar component, and button component. 
- Added Roboto and Rubik fonts.
- Removed Vite starter code. 

## Testing

- Manual testing

## Confirmation of Change

TODO

2024-02-08 06:23 UTC, kathyychenn approved these changes

2024-02-11 00:34 UTC, jaredsbt approved these changes

2024-02-12 06:54 UTC, Miyuki-L requested changes
Overall Good work for the first task so far. Lets get these changes implemented first. 

Also lets add this line `// eslint-disable-next-line @typescript-eslint/no-non-null-assertion` above line 7 of main.tsx . Root element is never null.

2024-02-16 05:36 UTC, Miyuki-L requested changes
Fantastic changes

2024-02-16 05:36 UTC, Miyuki-L commented on package-lock.json
This and package.json should be deleted. These should be in the frontend folder. 
WHen you ran npm install react-router-dom you did it in the root directory and so the project on my side is also not compiling.

2024-02-16 05:36 UTC, Miyuki-L commented on frontend/src/App.tsx
> +import AboutUs from "./pages/AboutUs.tsx";
One last thing lets add the exports for the pages and nav like how Kathy and Jared did for the pages. [here](https://github.com/TritonSE/CCIDC-Application-Overhaul/blob/7-home-page/frontend/src/pages/index.ts) One index.ts file for each folder and update the import statements.

2024-02-16 23:15 UTC, leo3friedman commented
ccidc.org navbar does not have link addresses for the resources nav, search, or cart. In our nav, search and cart do nothing and resources links to the base ccidc.org website.

2024-02-18 04:47 UTC, Miyuki-L approved these changes

2024-02-18 04:49 UTC, merged