Feature/personal info form
TritonSE/CCIDC-Application-Overhaul pull request #31
Opened 2024-03-12 02:57 UTC by kathyychenn

## Tracking Info

Resolves #12

## Changes

- created important facts section
- created formSection component to create individual sections
- created infoForm component for first step of path

## Testing

- tested long text for overflow, etc.

## Confirmation of Change

<img width="1624" alt="Screen Shot 2024-03-11 at 7 56 51 PM" src="https://github.com/TritonSE/CCIDC-Application-Overhaul/assets/97640717/07714c95-2099-4f9c-98c0-856fc4926207">

2024-04-08 19:21 UTC, emmaz12 approved these changes

2024-04-16 07:28 UTC, Madhav182003 approved these changes
Ran the code on my personal device. Everything is working as it should. There is no text overflow. Also ran lint check and everything is fine.

2024-04-30 07:34 UTC, Miyuki-L requested changes
Good work. Just address the compents and I think we'll be good

2024-04-30 07:34 UTC, Miyuki-L commented on frontend/src/components/Step2.tsx
> +                  <select className={styles.inputText} id="drop" required>
duplicated id. with the select for national exam

2024-04-30 21:17 UTC, kathyychenn commented on frontend/src/components/Step2.tsx
> +                onMouseEnter={() => {
sorry, what should i be fixing here?

2024-05-07 07:34 UTC, Miyuki-L reviewed
A few more changes to make and we'll be good

2024-05-07 07:34 UTC, Miyuki-L commented on frontend/src/components/Step1.tsx
> +              <select className={styles.inputText} id="drop" defaultValue={"default"} required>
duplicate id

2024-05-07 07:34 UTC, Miyuki-L commented on frontend/src/components/Step1.tsx
> +              <select className={styles.inputText} defaultValue={"default"} id="drop" required>
duplicate ID

2024-05-11 20:49 UTC, Miyuki-L approved these changes

2024-05-11 20:51 UTC, merged