Feature/sidhant/step5
TritonSE/CCIDC-Application-Overhaul pull request #54
Opened 2024-05-10 01:05 UTC by sidhantrohatgi

## Tracking Info

Resolves #14 

## Changes

Added Step 5

- TODO

## Testing

Ran the frontend and checked if the changes were reflected according to the figma

## Confirmation of Change

<img width="1440" alt="Screenshot 2024-05-09 at 18 03 34" src="https://github.com/TritonSE/CCIDC-Application-Overhaul/assets/118028422/42b29369-22fa-4a84-8367-fed7f83ec0a8">

2024-05-14 19:55 UTC, Miyuki-L reviewed
Looking good. Just a few things to clean up and also the button in the bottom navigator when on payment page

2024-05-14 19:55 UTC, Miyuki-L commented on frontend/src/components/Step5.tsx
> +              To pay via <strong className={styles.red}> credit card </strong>: Navigate to the
There is a extra space btw card and :

2024-05-14 19:56 UTC, Miyuki-L commented on frontend/src/components/Step5.tsx
> +      <form id="step5-form" onSubmit={onSubmit}>
Missing the border/shaow between the element and the background. 
![image](https://github.com/TritonSE/CCIDC-Application-Overhaul/assets/59126064/58a856f9-f0cc-4cd2-86e4-f7fa496b3be7)


See how there is a shadow/border on the top component but there isn't one on the bottom one

2024-05-17 23:57 UTC, leo3friedman requested changes
I had one question about why we use a form for Step5. Also, looks like you may want to merge main into this branch + resolve conflicts. Besides that, looks good!

2024-05-17 23:57 UTC, leo3friedman commented on frontend/src/components/Step5.tsx
> +  // Checks if all Required Inputs are filled before moving on to next step
I'm a little confused as to why Step5 is a form. Also, why we are checking that all required inputs are filled before moving on? From what I can tell the step has no inputs. Thanks

2024-11-21 04:10 UTC, Miyuki-L commented
#42

2024-11-21 04:10 UTC, closed without merging